[project]
name = "GameTrek"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.battle]
path = "contracts/battle.clar"
depends_on = []

[contracts.character]
path = "contracts/character.clar"
depends_on = []

[contracts.items]
path = "contracts/items.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
